import {
  EmojiHappyIcon,
  ChartSquareBarIcon,
  CursorClickIcon,
  DeviceMobileIcon,
  AdjustmentsIcon,
  SunIcon,
} from "@heroicons/react/outline";



const benefitOne = {
  title: "Highlight your benefits",
  desc: "You can use this space to highlight your first benefit or a feature of your product. It can also contain an image or Illustration like in the example along with some bullet points.",
  image: "/img/benefit-one.png",
  bullets: [
    {
      title: "Understand your customers",
      desc: "Then explain the first point breifly in one or two lines.",
      icon: <EmojiHappyIcon />,
    },
    {
      title: "Improve acquisition",
      desc: "Here you can add the next benefit point.",
      icon: <ChartSquareBarIcon />,
    },
    {
      title: "Drive customer retention",
      desc: "This will be your last bullet point in this section.",
      icon: <CursorClickIcon />,
    },
  ],
};

const benefitTwo = {
  title: "Offer more benefits here",
  desc: "You can use this same layout with a flip image to highlight your rest of the benefits of your product. It can also contain an image or Illustration as above section along with some bullet points.",
  image: "/img/benefit-two.png",
  bullets: [
    {
      title: "Mobile Responsive Template",
      desc: "Nextly is designed as a mobile first responsive template.",
      icon: <DeviceMobileIcon />,
    },
    {
      title: "Powered by Next.js & TailwindCSS",
      desc: "This template is powered by latest technologies and tools.",
      icon: <AdjustmentsIcon />,
    },
    {
      title: "Dark & Light Mode",
      desc: "Nextly comes with a zero-config light & dark mode. ",
      icon: <SunIcon />,
    },
  ],
};

const MentorData = [
  {
    name: "Jane Doe 1",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "About",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 2",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "About ",
    current: "SWE",
    companies: ["Apple", "Google"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 3",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 4",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 5",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 6",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 7",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi"],
    firstConsultationFree: "",
  },
  {
    name: "Jane Doe 8",
    avatar: "https://mdbootstrap.com/img/new/avatars/6.jpg",
    about: "",
    current: "SWE",
    companies: ["Apple", "Google", "Microsoft", "Coinbase"],
    experties: ["Backend", "Distributed system"],
    charge: "10$/hr",
    facebook: "#",
    instagram: "#",
    linkedin: "#",
    twitter: "#",
    lang: ["Hindi", "Eng"],
    firstConsultationFree: "",
  },
];

export { benefitOne, benefitTwo, MentorData };
